name: Deploy to Github Pages
on: 
  push:
    branches: 
      - 'main'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
      - name: Install and Build 🔧
        run: |
            npm config set @bit:registry https://node.bit.dev
            npm install
      - name: Deploy with gh-pages 🚀 # https://github.com/tschaub/gh-pages/pull/368
        run: | # add the git pull... when merging pull requests
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git pull origin main
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

